import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import Providers from '@/app/providers/Providers';
import { Sidebar } from '@/widgets/side-bar';

const plus_Jakarta_Sans = Plus_Jakarta_Sans({
    variable: '--font-plus-jakarta-sans',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: {
        default: 'Threadly',
        template: '%s | Threadly',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${plus_Jakarta_Sans.variable} ${plus_Jakarta_Sans.variable} ${plus_Jakarta_Sans.className} antialiased transition-colors duration-200`}
            >
                <Providers>
                    <main className="min-h-screen grid grid-cols-[310px_1fr] max-xl:grid-cols-[200px_1fr] max-lg:grid-cols-1">
                        <Sidebar
                            className={
                                'row-span-full col-start-1 max-lg:hidden'
                            }
                        />
                        <section
                            className={
                                'col-start-2 transition-colors duration-200'
                            }
                        >
                            {children}
                        </section>
                    </main>
                </Providers>
            </body>
        </html>
    );
}
